### ISSUE TITLE
Package Errors using GDK

### ISSUE THREAD

**Issue by PBSoloDeveloper** [microsoft/gdk-unity-package#102]
Hello.  This is a great plugin I hope the issue I see is just a config issue. 

When I select Build and include package for MS store (the check box)
It builds ok, I can run the app in the win32 folder.  But the manifest xml file that is produced contains errors. 

I was able to I believe fix all those up. But the GDK in unity create this file XboxDeveloperExperienceTe.GamePassSampleGame_1.0.0.0_x64__pmsd8ndztetqc.msixvc  and when I try to publish my app in the partner portal it says
The PublisherDisplayName element in the app manifest of XboxDeveloperExperienceTe.GamePassSampleGame_1.0.0.0_x64__pmsd8ndztetqc.msixvc is Xbox Developer Experience Team, which doesn't match your publisher display name

I Used the GDK Tool standalone as well and create what I think is a proper microsoftGame.config

How can you edit the msixvc properties?  or where are they derived from?

**Comment by tculotta** [comment]
Hello, can you verify you've followed these steps and your MicrosoftGame.config in Assets/GDK-Tools/ProjectMetadata/ contains the correct information for your title?
[Unity E2E guide: Associate your game with Microsoft Store](https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/get-started-with-pc-dev/get-started-with-unity-pc/gdk-unity-end-to-end-guide#associate-your-game-with-microsoft-store)

**Comment by PBSoloDeveloper** [comment]
Yes I was able to use the tool and associate the app it saved and created the MicrosftGame.ConfigI checked the folder you mentioned and it looks like its all in there? 




    On Wednesday, September 14, 2022 at 05:44:43 PM EDT, tculotta ***@***.***> wrote:  
 
 


Hello, can you verify you've followed these steps and your MicrosoftGame.config in Assets/GDK-Tools/ProjectMetadata/ contains the correct information for your title?
Unity E2E guide: Associate your game with Microsoft Store

**Comment by tculotta** [comment]
The MicrosoftGame.Config would already be created, but it seems like it still contains the sample title info included by default ([seen here](https://github.com/microsoft/gdk-unity-package/blob/main/Package/Assets/GDK-Tools/ProjectMetadata/MicrosoftGame.Config)) rather than the "Associate with the Microsoft Store" step replacing the necessary names/ids with your title's info from Partner Center. If your title info isn't being supplied in the .Config correctly, you can always fill in the correct info manually as a workaround, just by copying the correct ids and names from your Partner Center page.

I would recommend submitting this question to the [dev forums](https://forums.xboxlive.com/index.html) if you're set up as an approved Xbox developer as a next step since this would be a problem outside the plugin itself, whether it's an issue with the Association Wizard/Packaging tool or (more likely) a setup issue with your title in Partner Center. Otherwise I would suggest bringing the question to your Microsoft representative.

**Comment by PBSoloDeveloper** [comment]
Thank you for your help with this. 

    On Thursday, September 15, 2022 at 05:56:26 PM EDT, tculotta ***@***.***> wrote:  
 
 


The MicrosoftGame.Config would already be created, but it seems like it still contains the sample title info included by default (seen here) rather than the "Associate with the Microsoft Store" step replacing the necessary names/ids with your title's info from Partner Center. If your title info isn't being supplied in the .Config correctly, you can always fill in the correct info manually as a workaround, just by copying the correct ids and names from your Partner Center page.

I would recommend submitting this question to the dev forums if you're set up as an approved Xbox developer as a next step since this would be a problem outside the plugin itself, whether it's an issue with the Association Wizard/Packaging tool or (more likely) a setup issue with your title in Partner Center. Otherwise I would suggest bringing the question to your Microsoft representative.
